### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by Matsu-pt** [Matsu-pt/furima-35063#11]
https://furima-35063.herokuapp.com/
Basic認証
admin   4444
出品者用のメールアドレスとパスワード
test@test   123456q
購入者用のメールアドレスとパスワード
test2@test2  123456q

**Comment by takumi0530** [comment]
@Matsu-pt さん、ご提出ありがとうございます‼︎ お待たせしてしまい、申し訳ありません。
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

### **[修正依頼箇所]**

- [x] **パスワードは、6文字以上での入力が必須であること（6文字が入力されていれば、登録が可能なこと）**
6文字ですと登録ができませんでした。

修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by takumi0530** [comment]
@Matsu-pt さん、ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉
着実に技術力が身につき、実用的なアプリになってきてますね（^^）
これからもスタッフ一同応援しております🍀

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**
![最終課題終了_おめでとう画像2](https://user-images.githubusercontent.com/76197191/115672735-d0441500-a386-11eb-8d4d-dffbb905275d.png)
